extends: stylelint-config-standard
rules:
    indentation: 4
    declaration-block-trailing-semicolon: always
    declaration-colon-space-before: null
    selector-list-comma-newline-after: null
    comment-empty-line-before: null
    number-leading-zero: null
    number-no-trailing-zeros: null
    string-quotes: single
    function-url-quotes: never
    no-eol-whitespace: null
    font-family-name-quotes: always-unless-keyword
    font-family-no-missing-generic-family-keyword: null
    rule-empty-line-before: null
    max-empty-lines: 2

