FROM mhart/alpine-node
MAINTAINER Coderaiser

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install --production && \
    apk update && \
    apk add --no-cache bash make g++ python && \
    npm i gritty && \
    apk del make g++ python && \
    rm -rf /usr/include /tmp/* /var/cache/apk/*

COPY . /usr/src/app

ENV cloudcmd_terminal true
ENV cloudcmd_terminal_path gritty

EXPOSE 8000

ENTRYPOINT ["bin/cloudcmd.js"]

