name: Node CI
on:
  - push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: cloudcmd
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
          - 26.x
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: bun i redrun madrun -g --no-save
      - name: Install
        run: bun i --no-save
      - name: Init Madrun
        run: madrun --init
      - name: Lint
        run: redrun fix:lint
      - name: Typos
        uses: coderaiser/typos.ai@v1.1.8
        with:
          key: ${{ secrets.TYPOS_AI_KEY }}
      - name: Commit fixes
        uses: EndBug/add-and-commit@v10
        continue-on-error: true
        with:
          message: "chore: ${{ env.NAME }}: actions: lint ☘️"
      - name: Build
        run: redrun build
      - name: Test
        run: redrun test
      - name: Coverage
        run: redrun coverage coverage:report
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
